const actionTypes = {
  CLEAR_NOTES: 'CLEAR_NOTES',
  ADD_NOTE: 'ADD_NOTE',
  DEL_NOTE: 'DEL_NOTE',
  SET_NOTES: 'SET_NOTES',
  SHIFT_PITCH_RANGE: 'SHIFT_PITCH_RANGE',
  SET_QUESTION: 'SET_QUESTION',
  SET_BPM: 'SET_BPM',
  OPEN_SIGN_IN_DIALOG: 'OPEN_SIGN_IN_DIALOG',
  CLOSE_SIGN_IN_DIALOG: 'CLOSE_SIGN_IN_DIALOG',
  SET_USER: 'SET_USER',
  ADD_QUESTION_TO_LIST: 'ADD_QUESTION_TO_LIST',
  CLEAR_QUESTIONS_LIST: 'CLEAR_QUESTIONS_LIST',
  CHANGE_DISPLAY_MODE: 'CHANGE_DISPLAY_MODE',
  SET_LOW_BPM: 'SET_LOW_BPM',
  SET_HIGH_BPM: 'SET_HIGH_BPM',
  SET_TITLE: 'SET_TITLE',
  SET_QUESTION_ID: 'SET_QUESTION_ID',
};

export default actionTypes;
